version: '3'

services:
  angular-frontend:
    image: "angular-frontend:0.1.0"
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - fh
    env_file:
      - .env
  react-frontend:
    image: "react-frontend:0.1.0"
    container_name: react-frontend
    restart: unless-stopped
    ports:
      - "4201:80"
    networks:
      - fh
    env_file:
      - .env

networks:
  fh:
    driver: bridge